formula:
  - ansible:
  - wget:
  - flake8:
  - fortune:
  - yamllint:
  - git:
  - minikube:
  - tmux:
  - cask:
  - poetry:
  - go-task/tap/go-task:
  - pv:
  - watch:
  - rename:

  # k8s cluster tools
  - kubernetes-cli:
  - direnv:
  - flux:
  - age:
  - ipcalc:
  - jq:
  - sops:
  - terraform:
  - kustomize:
  - helm:
  - pre-commit:
  - prettier:

# taps:


# casks:
